// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "syncNoteIds": string;
      "syncPeriodSeconds": number;
      "syncAttachmentFolder": string;
      "sync.autoSyncLinkedNotes": boolean;
      "sync.background": boolean;
      "sync.externalEditQuietSeconds": number;
      "autoAnnotation": boolean;
      "insertLinkPosition": string;
      "workspace.outline.expandLevel": number;
      "workspace.outline.keepLinks": boolean;
      "editor.noteLinkPreviewType": string;
      "editor.useMagicKey": boolean;
      "editor.useMagicKeyShortcut": boolean;
      "editor.useMarkdownPaste": boolean;
      "editor.pinTableLeft": boolean;
      "editor.pinTableTop": boolean;
      "editor.customCSS": string;
      "editor.readableWidth": boolean;
      "editor.headingCollapse": boolean;
      "editor.codeHighlight": boolean;
      "editor.callouts": boolean;
      "editor.markdownInputRules": boolean;
      "editor.mathPreview": boolean;
      "exportNotes.takeover": boolean;
      "annotationNote.enableTagSync": boolean;
      "annotationNote.enableCreateNoteButton": boolean;
      "annotationColorLabel.ffd400": string;
      "annotationColorLabel.ff6666": string;
      "annotationColorLabel.5fb236": string;
      "annotationColorLabel.2ea8e5": string;
      "annotationColorLabel.a28ae5": string;
      "annotationColorLabel.e56eee": string;
      "annotationColorLabel.f19837": string;
      "annotationColorLabel.aaaaaa": string;
      "annotationSectionOrder": string;
      "settingsSync.enabled": boolean;
      "settingsSync.machineId": string;
      "settingsSync.lastSeen": string;
    };
  }
}
